jobs:
- spark_job:
    args:
    - --inputPath=gs://your_bucket/mock_input_data_path/
    - --outputPath=gs://your_bucket/data_output_path/
    main_jar_file_uri: gs://your_bucket/spark_app.jar
  step_id: batch-gcs-gcs-workflow
placement:
  managed_cluster:
    cluster_name: your-managed-cluster-name
    config:
      gce_cluster_config:
        zone_uri: us-central1-b
      master_config:
        num_instances: 1
      worker_config:
        num_instances: 3