#!/bin/bash
#
# Startup script for the Squid Proxy VM.
# This script is executed automatically on the first boot of the instance.

set -e
set -x

# --- Installation ---
# Update package lists and install Squid silently.
export DEBIAN_FRONTEND=noninteractive
apt-get -q update
apt-get -q install -y squid

# --- Configuration ---

# Fetch the internal subnet range from the GCE metadata server.
# This value is passed in during the 'gcloud compute instances create' command.
INTERNAL_SUBNET_RANGE=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/internal_subnet_range)

if [[ -z "${INTERNAL_SUBNET_RANGE}" ]]; then
  echo "FATAL: Could not determine internal subnet range from instance metadata." >&2
  exit 1
fi

# Backup the original squid configuration
mv /etc/squid/squid.conf /etc/squid/squid.conf.original

# Create a new, secure squid.conf from scratch.
# This configuration only allows access from the specified internal subnet.
cat <<EOF > /etc/squid/squid.conf
#
# Squid Proxy Configuration - Generated by CUJ startup script
#

# Define an Access Control List (ACL) for the internal private network
acl internal_network src ${INTERNAL_SUBNET_RANGE}

# Define standard ports
acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 443         # https
acl CONNECT method CONNECT

# Deny requests to non-standard ports
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# Allow access only from our internal network.
# The 'deny all' rule is crucial for security.
http_access allow internal_network
http_access deny all

# Listen on the standard proxy port 3128 on all available interfaces
http_port 0.0.0.0:3128

# Use Google's reliable public DNS servers
dns_nameservers 8.8.8.8 8.8.4.4

# Turn off Via and other headers for cleaner requests
via off
forwarded_for off
request_header_access From deny all
request_header_access Server deny all
request_header_access User-Agent deny all
request_header_access WWW-Authenticate deny all
request_header_access Link deny all

# Recommended performance and security settings
cache_dir ufs /var/spool/squid 100 16 256
coredump_dir /var/spool/squid
refresh_pattern .         0       20%     1440
EOF

# --- Enable IP Forwarding ---
# This is necessary for the dual-NIC VM to route traffic from the internal
# network to the external one.
echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
sysctl -p

# --- Restart Service ---
# Restart squid to apply the new configuration.
systemctl restart squid

echo "Squid proxy installation and configuration complete."
